name: volcano
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.0.5
  spotlightnavbar: ^0.0.3
  nav_router: ^0.0.5
  shared_preferences: ^0.5.6+3
  provider: ^4.0.5
  dot_pagination_swiper: ^0.1.1
  timeline_list: ^0.0.5

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/brain/
    - assets/Cube/
    - assets/images/
