name: volcano
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  flutter_cube: ^0.0.5
  spotlightnavbar: ^0.0.5
  nav_router: ^0.0.5
  shared_preferences: ^0.5.6+3
  provider: ^4.0.5
  dot_pagination_swiper: ^0.1.1
  timeline_list: ^0.0.5
  font_awesome_flutter: ^8.8.1
  google_fonts: ^0.6.2
  flare_flutter: ^2.0.3
  badges: ^1.1.1
  flutter_circular_text: "^0.3.0"
  gradient_text: ^1.0.2
  flutter_spinkit: "^4.1.2"
  image_picker: ^0.6.5+2 
  step_progress_indicator: ^0.2.2+5
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

flutter_native_splash:
  image: assets/images/splash.png
  color: "000000"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconHigh.png"

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/brain/
    - assets/Cube/
    - assets/images/
    - assets/rive/
